In [2]:
import pandas as pd

from src.pair_eligibility import screen_pairs, get_eligible_pairs, save_screening_results

In [3]:
pairs = pd.read_parquet("data/processed/ou_results.parquet")
pairs.head()

,pair,dependent,independent,mean,std,min spread,max spread,theta,half_life,expected_convergence,hurst,current z
0,V-MA,V,MA,-4.110665e-15,0.024864,-0.067772,0.081673,0.039095,17.729867,53.189602,0.360835,-0.946981
1,NWS-NWSA,NWS,NWSA,-3.981402e-16,0.017107,-0.116219,0.036461,0.038747,17.888873,53.666619,0.285465,1.000233
2,MLM-VMC,MLM,VMC,1.383114e-14,0.049987,-0.182892,0.273007,0.038179,18.155329,54.465986,0.283777,-0.970178
3,HLT-AXP,HLT,AXP,-2.222718e-15,0.068528,-0.268255,0.190885,0.035402,19.579342,58.738026,0.313413,0.338066
4,GOOGL-GOOG,GOOGL,GOOG,2.234584e-15,0.007476,-0.033790,0.018120,0.035110,19.742112,59.226335,0.353314,-0.630847

In [4]:
screened_pairs = screen_pairs(pairs)

screened_pairs

,pair,dependent,independent,mean,std,min spread,max spread,theta,half_life,expected_convergence,...,stock1_has_options,stock2_has_options,stock1_num_expirations,stock2_num_expirations,stock1_first_expiration,stock2_first_expiration,stock1_last_expiration,stock2_last_expiration,eligible,exclusion_reason
0,V-MA,V,MA,-4.110665e-15,0.024864,-0.067772,0.081673,0.039095,17.729867,53.189602,...,True,True,18,16,2026-08-21,2026-08-21,2028-12-15,2028-12-15,True,None
1,NWS-NWSA,NWS,NWSA,-3.981402e-16,0.017107,-0.116219,0.036461,0.038747,17.888873,53.666619,...,True,True,4,4,2026-08-21,2026-08-21,2027-01-15,2027-01-15,False,Same issuer / share class
2,MLM-VMC,MLM,VMC,1.383114e-14,0.049987,-0.182892,0.273007,0.038179,18.155329,54.465986,...,True,True,6,4,2026-08-21,2026-08-21,2027-12-17,2027-02-19,True,None
3,HLT-AXP,HLT,AXP,-2.222718e-15,0.068528,-0.268255,0.190885,0.035402,19.579342,58.738026,...,True,True,12,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
4,GOOGL-GOOG,GOOGL,GOOG,2.234584e-15,0.007476,-0.033790,0.018120,0.035110,19.742112,59.226335,...,True,True,22,18,2026-08-19,2026-08-21,2028-12-15,2028-12-15,False,Same issuer / share class
5,SHW-HD,SHW,HD,-1.124588e-14,0.056705,-0.156361,0.178546,0.034308,20.203513,60.610538,...,True,True,7,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
6,URI-MS,URI,MS,-4.401002e-15,0.087648,-0.277321,0.274505,0.033124,20.925609,62.776828,...,True,True,12,16,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
7,LYV-AXP,LYV,AXP,-3.641582e-15,0.094060,-0.308480,0.220129,0.032314,21.450283,64.350850,...,True,True,15,17,2026-08-21,2026-08-21,2028-06-16,2028-12-15,True,None
8,SPGI-MCO,SPGI,MCO,-1.057331e-15,0.040006,-0.168375,0.118095,0.032197,21.528180,64.584540,...,True,True,16,5,2026-08-21,2026-08-21,2028-01-21,2027-02-19,True,None
9,MDLZ-PG,MDLZ,PG,-7.521745e-15,0.043512,-0.141182,0.102005,0.031513,21.995870,65.987609,...,True,True,12,14,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
10,PEP-HSY,PEP,HSY,-9.217565e-15,0.041325,-0.120839,0.141033,0.029673,23.359554,70.078662,...,True,True,14,14,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
11,ADI-CDW,ADI,CDW,9.291790e-15,0.068122,-0.218436,0.211842,0.029138,23.788271,71.364812,...,True,True,12,5,2026-08-21,2026-08-21,2028-01-21,2027-03-19,True,None
12,KEY-CFG,KEY,CFG,6.230882e-16,0.037848,-0.103061,0.088978,0.028668,24.178542,72.535627,...,True,True,10,7,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
13,V-ROP,V,ROP,-1.921576e-14,0.062391,-0.234330,0.194241,0.028653,24.191248,72.573744,...,True,True,18,4,2026-08-21,2026-08-21,2028-12-15,2027-02-19,True,None
14,ORCL-ETN,ORCL,ETN,5.619912e-15,0.065521,-0.183481,0.205558,0.028352,24.448179,73.344537,...,True,True,19,13,2026-08-21,2026-08-21,2028-12-15,2028-01-21,True,None
15,RMD-PODD,RMD,PODD,3.382046e-15,0.095808,-0.237478,0.256217,0.027768,24.961659,74.884976,...,True,True,4,5,2026-08-21,2026-08-21,2027-01-15,2027-12-17,True,None
16,DUK-KO,DUK,KO,-1.038396e-15,0.047934,-0.122904,0.118046,0.027604,25.110189,75.330568,...,True,True,8,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
17,FANG-EOG,FANG,EOG,-4.584798e-15,0.088204,-0.489459,0.277190,0.027226,25.458676,76.376027,...,True,True,9,14,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
18,CDW-KEYS,CDW,KEYS,6.776716e-15,0.074252,-0.277521,0.166604,0.026318,26.337379,79.012138,...,True,True,5,6,2026-08-21,2026-08-21,2027-03-19,2027-02-19,True,None
19,ROP-MA,ROP,MA,3.004356e-16,0.057387,-0.201200,0.195864,0.025762,26.905358,80.716074,...,True,True,4,16,2026-08-21,2026-08-21,2027-02-19,2028-12-15,True,None
20,MCO-ZTS,MCO,ZTS,-6.832258e-15,0.063585,-0.201375,0.158535,0.025588,27.088971,81.266914,...,True,True,5,8,2026-08-21,2026-08-21,2027-02-19,2028-01-21,True,None
21,NDSN-ITW,NDSN,ITW,-1.934906e-15,0.072273,-0.304059,0.205361,0.025187,27.519492,82.558475,...,True,True,4,6,2026-08-21,2026-08-21,2027-03-19,2027-03-19,True,None
22,IBM-PFG,IBM,PFG,-1.034104e-15,0.059532,-0.188954,0.148384,0.024848,27.895381,83.686143,...,True,True,18,4,2026-08-21,2026-08-21,2028-12-15,2027-01-15,True,None
23,MKC-CHD,MKC,CHD,1.403716e-16,0.059980,-0.186057,0.169725,0.024792,27.958347,83.875041,...,True,True,6,5,2026-08-21,2026-08-21,2027-06-17,2027-01-15,True,None
24,MRSH-RSG,MRSH,RSG,-8.515707e-15,0.050386,-0.136723,0.118702,0.024568,28.212962,84.638886,...,True,True,6,4,2026-08-21,2026-08-21,2028-01-21,2027-01-15,True,None
25,NTRS-BAC,NTRS,BAC,-1.698597e-15,0.053748,-0.240396,0.116899,0.024566,28.215158,84.645475,...,True,True,6,19,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
26,PHM-NVR,PHM,NVR,1.879363e-15,0.074913,-0.347975,0.185916,0.023928,28.968134,86.904403,...,True,False,13,0,2026-08-21,None,2028-01-21,None,False,Options unavailable for one or both underlyings
27,CMS-WEC,CMS,WEC,2.990722e-15,0.029467,-0.126747,0.077959,0.023751,29.183473,87.550418,...,True,True,4,5,2026-08-21,2026-08-21,2027-03-19,2027-01-15,True,None
28,UNP-NSC,UNP,NSC,4.795861e-15,0.045644,-0.106229,0.129476,0.023689,29.260228,87.780683,...,True,True,16,7,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
29,ETN-JBL,ETN,JBL,1.195683e-15,0.084655,-0.293842,0.255716,0.023688,29.261319,87.783958,...,True,True,13,12,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
30,WEC-DG,WEC,DG,-1.129941e-14,0.071523,-0.180623,0.258444,0.023681,29.269854,87.809563,...,True,True,5,14,2026-08-21,2026-08-21,2027-01-15,2028-01-21,True,None
31,ABT-STE,ABT,STE,-6.019820e-15,0.064714,-0.180944,0.206665,0.023626,29.338606,88.015819,...,True,True,16,4,2026-08-21,2026-08-21,2028-03-17,2027-03-19,True,None
32,SHW-DHI,SHW,DHI,6.236941e-15,0.089779,-0.219932,0.392357,0.023557,29.424301,88.272902,...,True,True,7,14,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
33,MAS-DHI,MAS,DHI,-5.200817e-16,0.065308,-0.237454,0.139442,0.023549,29.433634,88.300902,...,True,True,4,14,2026-08-21,2026-08-21,2027-01-15,2028-01-21,True,None
34,WMT-V,WMT,V,7.893124e-15,0.073872,-0.183292,0.199332,0.023537,29.449532,88.348597,...,True,True,17,18,2026-08-21,2026-08-21,2028-12-15,2028-12-15,True,None
35,WELL-AVB,WELL,AVB,-4.492143e-15,0.078935,-0.542973,0.151875,0.023509,29.483770,88.451310,...,True,True,10,4,2026-08-21,2026-08-21,2027-11-19,2027-01-15,True,None
36,SHW-RMD,SHW,RMD,2.825609e-15,0.084203,-0.349709,0.238057,0.023394,29.629032,88.887095,...,True,True,7,4,2026-08-21,2026-08-21,2028-01-21,2027-01-15,True,None
37,NTRS-PNC,NTRS,PNC,1.835636e-14,0.056086,-0.242591,0.142965,0.023388,29.637306,88.911919,...,True,True,6,16,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
38,ETN-KLAC,ETN,KLAC,5.542153e-15,0.076428,-0.301874,0.185175,0.023255,29.805948,89.417843,...,True,True,13,13,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
39,ES-WEC,ES,WEC,3.538323e-15,0.033349,-0.092883,0.142163,0.023232,29.835468,89.506405,...,True,True,4,5,2026-08-21,2026-08-21,2027-01-15,2027-01-15,True,None

In [5]:
screened_pairs[
    ~screened_pairs["eligible"]
][
    [
        "pair",
        "half_life",
        "same_issuer",
        "stock1_has_options",
        "stock2_has_options",
        "exclusion_reason",
    ]
]

,pair,half_life,same_issuer,stock1_has_options,stock2_has_options,exclusion_reason
1,NWS-NWSA,17.888873,True,True,True,Same issuer / share class
4,GOOGL-GOOG,19.742112,True,True,True,Same issuer / share class
26,PHM-NVR,28.968134,False,True,False,Options unavailable for one or both underlyings

In [6]:
selected_pairs = get_eligible_pairs(
    screened_pairs,
    n_pairs=20,
)

selected_pairs

,pair,dependent,independent,mean,std,min spread,max spread,theta,half_life,expected_convergence,...,stock1_has_options,stock2_has_options,stock1_num_expirations,stock2_num_expirations,stock1_first_expiration,stock2_first_expiration,stock1_last_expiration,stock2_last_expiration,eligible,exclusion_reason
0,V-MA,V,MA,-4.110665e-15,0.024864,-0.067772,0.081673,0.039095,17.729867,53.189602,...,True,True,18,16,2026-08-21,2026-08-21,2028-12-15,2028-12-15,True,None
1,MLM-VMC,MLM,VMC,1.383114e-14,0.049987,-0.182892,0.273007,0.038179,18.155329,54.465986,...,True,True,6,4,2026-08-21,2026-08-21,2027-12-17,2027-02-19,True,None
2,HLT-AXP,HLT,AXP,-2.222718e-15,0.068528,-0.268255,0.190885,0.035402,19.579342,58.738026,...,True,True,12,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
3,SHW-HD,SHW,HD,-1.124588e-14,0.056705,-0.156361,0.178546,0.034308,20.203513,60.610538,...,True,True,7,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
4,URI-MS,URI,MS,-4.401002e-15,0.087648,-0.277321,0.274505,0.033124,20.925609,62.776828,...,True,True,12,16,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
5,LYV-AXP,LYV,AXP,-3.641582e-15,0.094060,-0.308480,0.220129,0.032314,21.450283,64.350850,...,True,True,15,17,2026-08-21,2026-08-21,2028-06-16,2028-12-15,True,None
6,SPGI-MCO,SPGI,MCO,-1.057331e-15,0.040006,-0.168375,0.118095,0.032197,21.528180,64.584540,...,True,True,16,5,2026-08-21,2026-08-21,2028-01-21,2027-02-19,True,None
7,MDLZ-PG,MDLZ,PG,-7.521745e-15,0.043512,-0.141182,0.102005,0.031513,21.995870,65.987609,...,True,True,12,14,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
8,PEP-HSY,PEP,HSY,-9.217565e-15,0.041325,-0.120839,0.141033,0.029673,23.359554,70.078662,...,True,True,14,14,2026-08-21,2026-08-21,2028-01-21,2028-01-21,True,None
9,ADI-CDW,ADI,CDW,9.291790e-15,0.068122,-0.218436,0.211842,0.029138,23.788271,71.364812,...,True,True,12,5,2026-08-21,2026-08-21,2028-01-21,2027-03-19,True,None
10,KEY-CFG,KEY,CFG,6.230882e-16,0.037848,-0.103061,0.088978,0.028668,24.178542,72.535627,...,True,True,10,7,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
11,V-ROP,V,ROP,-1.921576e-14,0.062391,-0.234330,0.194241,0.028653,24.191248,72.573744,...,True,True,18,4,2026-08-21,2026-08-21,2028-12-15,2027-02-19,True,None
12,ORCL-ETN,ORCL,ETN,5.619912e-15,0.065521,-0.183481,0.205558,0.028352,24.448179,73.344537,...,True,True,19,13,2026-08-21,2026-08-21,2028-12-15,2028-01-21,True,None
13,RMD-PODD,RMD,PODD,3.382046e-15,0.095808,-0.237478,0.256217,0.027768,24.961659,74.884976,...,True,True,4,5,2026-08-21,2026-08-21,2027-01-15,2027-12-17,True,None
14,DUK-KO,DUK,KO,-1.038396e-15,0.047934,-0.122904,0.118046,0.027604,25.110189,75.330568,...,True,True,8,17,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
15,FANG-EOG,FANG,EOG,-4.584798e-15,0.088204,-0.489459,0.277190,0.027226,25.458676,76.376027,...,True,True,9,14,2026-08-21,2026-08-21,2028-01-21,2028-12-15,True,None
16,CDW-KEYS,CDW,KEYS,6.776716e-15,0.074252,-0.277521,0.166604,0.026318,26.337379,79.012138,...,True,True,5,6,2026-08-21,2026-08-21,2027-03-19,2027-02-19,True,None
17,ROP-MA,ROP,MA,3.004356e-16,0.057387,-0.201200,0.195864,0.025762,26.905358,80.716074,...,True,True,4,16,2026-08-21,2026-08-21,2027-02-19,2028-12-15,True,None
18,MCO-ZTS,MCO,ZTS,-6.832258e-15,0.063585,-0.201375,0.158535,0.025588,27.088971,81.266914,...,True,True,5,8,2026-08-21,2026-08-21,2027-02-19,2028-01-21,True,None
19,NDSN-ITW,NDSN,ITW,-1.934906e-15,0.072273,-0.304059,0.205361,0.025187,27.519492,82.558475,...,True,True,4,6,2026-08-21,2026-08-21,2027-03-19,2027-03-19,True,None

In [7]:
save_screening_results(
    screened_pairs=screened_pairs,
    eligible_pairs=selected_pairs,
    screening_path="data/processed/pair_screening.parquet",
    selected_path="data/processed/selected_pairs.parquet",
)